bot:
    id: 1063655311
    regname: 'BotMarsFramework'
    password: 'password here'
    chat: 2594913
    name: 'Bot Ruby'
    avatar: 'http://i.imgur.com/SS3qHms.png'
    homepage: 'https://github.com/Xety/MarsBot'

debug: true
